version: "3.8"
services:
    postgres:
        container_name: database_postgresql
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=galo
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=mibasegalo
            - POSTGRES_HOST=localhost
        volumes:
            - ./db:/var/lib/postgresql/data
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: servidor-php
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./html:/var/www/html
    django_app:
        build:
            context: ./
            dockerfile: DockerfileDjango
        container_name: webapp_django
        restart: always
        volumes:
            - ./djangoapp:/application
        ports:
            - 5000:5000
        command: python manage.py runserver 0.0.0.0:5000
volumes:
    html: {}
    db: {}

